services:
  patch-manager:
    build:
      context: .
      args:
        COPA_VERSION: ${COPA_VERSION:-0.14.1}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./database:/app/database
      - ./output:/app/output
    environment:
      PORT: '5432'
      PATCH_SCHEDULE: '0 2 * * *'
      PATCH_CONCURRENCY: '3'
    ports:
      - '${PORT:-5432}:${PORT:-5432}'
    restart: unless-stopped
